export const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS';
export const GET_STOCK_SUCCESS = 'GET_STOCK_SUCCESS';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const ORDER_BUY_SUCCESS = 'ORDER_BUY_SUCCESS';

export const ORDER_SELL_SUCCESS = 'ORDER_SELL_SUCCESS';

export const CLEAR = 'CLEAR';